### ISSUE TITLE
loss of keyword labels

### ISSUE THREAD

**Issue by tobiasko** [chambm/AhoCorasickTrie#2]
Dear Matt,

the AhoCorasickTrie search does a super fast job. Really cool. I tried to do the same with the normal pattern matching functions from bioc Biostrings, but that took forever. Martin Morgan finally advised me to try your package. But I have a little problem regarding how it deals with names/labels of keywords. Here is an example from my code:

```
ref.proteome <- readAAStringSet(filepath = "uniprot-proteome_UP000000589.fasta")
n <- 10
peptides <- strip.mods(strip.ends(GluC.endpoint.peptide$ComparisonResult$Protein[1:n])) #first 10 peptides
names(peptides) <- GluC.endpoint.peptide$ComparisonResult$Protein[1:n] #put mod peptide as labels
proteins <- BiocGenerics::sapply(ref.proteome, toString) # full reference proteome
l <- AhoCorasickSearch(keywords = peptides, text = proteins, alphabet = "aminoacid", groupByKeyword = TRUE)


```
So far everything works perfectly, but the returned data structure looks like:

```
> head(l)
$ADLAEEYSKDR
$ADLAEEYSKDR[[1]]
$ADLAEEYSKDR[[1]]$Text
[1] "sp|P68037|UB2L3_MOUSE Ubiquitin-conjugating enzyme E2 L3 OS=Mus musculus GN=Ube2l3 PE=1 SV=1"

$ADLAEEYSKDR[[1]]$Offset
[1] 123



$ADLIAYLKKATNE
$ADLIAYLKKATNE[[1]]
$ADLIAYLKKATNE[[1]]$Text
[1] "sp|P62897|CYC_MOUSE Cytochrome c, somatic OS=Mus musculus GN=Cycs PE=1 SV=2"

$ADLIAYLKKATNE[[1]]$Offset
[1] 93

...

```
The labels of the keywords are lost! Instead the keywords as such are used as labels. Remember I took care to have a named vector of keywords (peptides) to not lose the associated modification pattern:

```
> names(peptides)
 [1] "AAC[+57.0]YTK[+28.0]LLE"              "AAK[+28.0]LAPEFAK[+28.0]R"          
 [3] "AAMQQDPVASSHK[+28.0]IDAK[+28.0]TYR"   "AASQPGELK[+28.0]DWFVGR"             
 [5] "AC[+57.0]IPQSFTVDSSK[+28.0]AGLAPLEVR" "ADGYVLEGK[+28.0]EL"                 
 [7] "ADLAEEYSK[+28.0]DR"                   "ADLEC[+57.0]TK[+28.0]PAA"           
 [9] "ADLIAYLK[+28.0]K[+28.0]ATNE"          "ADLPTLGFTHFQPAQLTTVGK[+28.0]R"   

```
Would it be possible to tweek the package in a way that the keyword AND text labels are preserved in the data structure returned by the matching function?

Greetings,

Tobias Kockmann

**Comment by tobiasko** [comment]
Hi Matt,

I tried to write a work around by putting the names of the keywords back into the list-of-list, but here is the next complication: AhoCorasickSearch() does not preserve the order of the keywords.
```
for(i in 1:length(l)){
  l[[i]]["mod.pep"] <- names(peptides)[i] 
}
> head(l)
$ADLECTKPAA
$ADLECTKPAA[[1]]
$ADLECTKPAA[[1]]$Text
[1] "sp|P01027|CO3_MOUSE Complement C3 OS=Mus musculus GN=C3 PE=1 SV=3"

$ADLECTKPAA[[1]]$Offset
[1] 657


$ADLECTKPAA$mod.pep
[1] "AAC[+57.0]YTK[+28.0]LLE"
```
I am really stuck here!

**Comment by chambm** [comment]
Hi Tobias, glad you find the package useful. I don't see any reason that we can't keep labels for the keywords, I just didn't have that in mind when I implemented it. However, you should be able to workaround it by creating a map from keyword to mod.pep, instead of just using index. I.e. use keyword as the key instead of index `i`.

**Comment by tobiasko** [comment]
Hi Matt,

I think this does not work, because if you strip two modified peptides (e.g. [+28]XXKXXR, [+28]XXK[+28]XXR) you get the identical character string: XXKXXR. If now the character string becomes the keyword and you would like to do the inverse mapping (by string matching...jip the mapping is not unique anymore. If the order of the list-of-list elements would be equal to the order of the keyword list one could use this trick to map back, but...

```
> peptides
                       1                        2                        3                        4 
             "AACYTKLLE"            "AAKLAPEFAKR"   "AAMQQDPVASSHKIDAKTYR"        "AASQPGELKDWFVGR" 
                       5                        6                        7                        8 
"ACIPQSFTVDSSKAGLAPLEVR"            "ADGYVLEGKEL"            "ADLAEEYSKDR"             "ADLECTKPAA" 
                       9                       10 
         "ADLIAYLKKATNE" "ADLPTLGFTHFQPAQLTTVGKR" 
> names(l)
 [1] "ADLECTKPAA"             "ADGYVLEGKEL"            "AASQPGELKDWFVGR"       
 [4] "ADLPTLGFTHFQPAQLTTVGKR" "ADLAEEYSKDR"            "AAKLAPEFAKR"           
 [7] "AACYTKLLE"              "ACIPQSFTVDSSKAGLAPLEVR" "AAMQQDPVASSHKIDAKTYR"  
[10] "ADLIAYLKKATNE"         
``` 
it is not. Last resort I can think of: Can one somehow prevent the sorting? Or can I pre-sort the keyword list, so the order gets preserved

Greetings,
Tobi

**Comment by chambm** [comment]
If you pass in duplicate keywords those are going to get collapsed by the algorithm, there's no avoiding that. What's the problem with not having a unique mapping? If two or more mod.peps map to the same keyword, they will all share the same instances in the protein sequences, regardless of whether there was a unique mapping or not. What's the difference between:

     PEPTTIDE(PEPTT[80]IDE): protein1:42
     PEPTTIDE(PEPT[80]TIDE): protein1:42

and

    PEPTTIDE(PEPTT[80]IDE,PEPT[80]TIDE): protein1:42

**Comment by tobiasko** [comment]
Hi Matt,

yes you are right - I didn't even think of the possibility that the algorithm could collapse the keywords. I will need to take care of that by something like a left-join using the stripped sequences as keys. Thx for making this clear!
